[[main]]
  name = "About"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Mentorship"
  pageRef = "teaching"
  weight = 50

[[main]]
  name = "Presentation"
  pageRef = "presentation"
  weight = 40

[[main]]
  name = "CV"
  url = "/cv-2026-09-30.pdf"
  weight = 60
